export const validTimezones = [
    "est",
    "cst",
    "mst",
    "pst",
    "akst",
    "hst",
    "gmt",
    "cet",
    "eet",
    "west",
    "cat",
    "eat",
    "msk",
    "ist",
    "cst_china",
    "jst",
    "kst",
    "ist_indonesia",
    "awst",
    "acst",
    "aest",
    "nzst",
    "fjt",
    "art",
    "bot",
    "brt",
    "clt",
] as const;
export const blocknotes = [
    {
        id: 1,
        title: "Hidden gems",
        last_modified: "15/4/2024, 12:12:45 PM",
    },
    {
        id: 2,
        title: "Hot now",
        last_modified: "15/4/2024, 12:12:45 PM",
    },
    {
        id: 3,
        title: "Tristan’s notes",
        last_modified: "15/4/2024, 12:12:45 PM",
    },
    {
        id: 4,
        title: "Maria’s notes",
        last_modified: "15/4/2024, 12:12:45 PM",
    },
    {
        id: 5,
        title: "Evelyn’s notes",
        last_modified: "15/4/2024, 12:12:45 PM",
    },
    {
        id: 6,
        title: "Mark’s notes",
        last_modified: "15/4/2024, 12:12:45 PM",
    },
];
